version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: william-postgres
    restart: always
    env_file:
      - .env
      - .env.production
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./__data/postgres/:/var/lib/postgresql/data/
      - ./deploy/sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - william_net

  redis:
    image: redis:alpine
    container_name: william-redis
    restart: always
    env_file:
      - .env
      - .env.production
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - william_net

  william-server:
    build:
      context: .
      args:
        - PROJECT_DIR=${PROJECT_DIR}
    image: william-server:stable
    container_name: william-server
    restart: always
    env_file:
      - .env
      - .env.production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./logs/:${PROJECT_DIR}/logs/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - william_net

networks:
  william_net:
    name: william_net
