export enum ErrorEnum {
  DEFAULT = '0:Unknown error',
  SERVER_ERROR = '500:Server busy, please try again later',

  SYSTEM_USER_EXISTS = '1001:System user already exists',
  INVALID_VERIFICATION_CODE = '1002:Invalid verification code',
  INVALID_USERNAME_PASSWORD = '1003:Invalid username or password',
  NODE_ROUTE_EXISTS = '1004:Node route already exists',
  PERMISSION_REQUIRES_PARENT = '1005:Permission must include parent node',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '1006:Illegal operation: this node only supports directory type parent node',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '1007:Illegal operation: node type cannot be directly converted',
  ROLE_HAS_ASSOCIATED_USERS = '1008:This role has associated users, please delete associated users first',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '1009:This department has associated users, please delete associated users first',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '1010:This department has associated roles, please delete associated roles first',
  PASSWORD_MISMATCH = '1011:Old password does not match original password',
  LOGOUT_OWN_SESSION = '1012:To logout yourself, please use the logout button in the top right corner',
  NOT_ALLOWED_TO_LOGOUT_USER = '1013:Not allowed to logout this user',
  PARENT_MENU_NOT_FOUND = '1014:Parent menu does not exist',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '1015:This department has child departments, please delete child departments first',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '1016:System built-in functions are not allowed to be operated',
  USER_NOT_FOUND = '1017:User does not exist',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '1018:Unable to find department for current user',
  DEPARTMENT_NOT_FOUND = '1019:Department does not exist',
  PARAMETER_CONFIG_KEY_EXISTS = '1022:Parameter configuration key-value pair already exists',
  DEFAULT_ROLE_NOT_FOUND = '1023:Assigned default role does not exist',

  INVALID_LOGIN = '1101:Invalid login, please login again',
  NO_PERMISSION = '1102:No permission to access',
  ONLY_ADMIN_CAN_LOGIN = '1103:Not an administrator, cannot login',
  REQUEST_INVALIDATED = '1104:Current request has expired',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '1105:Your account has been logged in elsewhere',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '1106:Guest account operations are not allowed',
  REQUESTED_RESOURCE_NOT_FOUND = '1107:Requested resource does not exist',

  OAUTH_ALREADY_LINKED = '1108:This OAuth account is already linked to another user',
  OAUTH_PROVIDER_NOT_FOUND = '1109:OAuth provider not found for this user',
  OAUTH_EMAIL_REQUIRED = '1110:Email is required for OAuth registration',
  INVALID_OTP = '1111:Invalid or incorrect OTP code',
  OTP_EXPIRED = '1112:OTP code has expired, please request a new one',
  TOO_MANY_OTP_ATTEMPTS = '1113:Too many failed attempts, please request a new OTP',
  TOO_MANY_OTP_REQUESTS = '1114:Too many OTP requests, please try again later',

  TOO_MANY_REQUESTS = '1201:Request frequency too fast, please try again in one minute',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '1202:Maximum 5 verification codes per day',
  VERIFICATION_CODE_SEND_FAILED = '1203:Verification code send failed',

  INSECURE_MISSION = '1301:Insecure mission, ensure execution is added with @Mission annotation',
  EXECUTED_MISSION_NOT_FOUND = '1302:Executed mission does not exist',
  MISSION_EXECUTION_FAILED = '1303:Mission execution failed',
  MISSION_NOT_FOUND = '1304:Mission does not exist',

  OSS_FILE_OR_DIR_EXIST = '1401:File or directory to be created already exists',
  OSS_NO_OPERATION_REQUIRED = '1402:No operation required',
  OSS_EXCEE_MAXIMUM_QUANTITY = '1403:Exceeded maximum supported processing quantity',
}
